import React, { useState } from "react";

const SeatLayout = () => {
  const [selectedSeats, setSelectedSeats] = useState([]);

  const handleSeatClick = (seatNumber) => {
    if (selectedSeats.includes(seatNumber)) {
      setSelectedSeats(selectedSeats.filter((seat) => seat !== seatNumber));
    } else {
      setSelectedSeats([...selectedSeats, seatNumber]);
    }
  };

  return (
    <div className="mt-5">
      <div className="seatBox">
        <h4>Seat Layout</h4>
        <div className="seat-container">
          <div className="row">
            <Seat
              seatNumber="A1"
              className="seat"
              isSelected={selectedSeats.includes("A1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A2"
              className="seat"
              isSelected={selectedSeats.includes("A2")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A1"
              className="seat"
              isSelected={selectedSeats.includes("A1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A2"
              className="seat"
              isSelected={selectedSeats.includes("A2")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A1"
              className="seat"
              isSelected={selectedSeats.includes("A1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A2"
              className="seat"
              isSelected={selectedSeats.includes("A2")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A1"
              className="seat"
              isSelected={selectedSeats.includes("A1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A2"
              className="seat"
              isSelected={selectedSeats.includes("A2")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A1"
              className="seat"
              isSelected={selectedSeats.includes("A1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A2"
              className="seat"
              isSelected={selectedSeats.includes("A2")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A1"
              className="seat"
              isSelected={selectedSeats.includes("A1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A2"
              className="seat"
              isSelected={selectedSeats.includes("A2")}
              onClick={handleSeatClick}
            />
          </div>
          <div className="row">
            <Seat
              seatNumber="B1"
              className="seat"
              isSelected={selectedSeats.includes("B1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="B2"
              className="seat"
              isSelected={selectedSeats.includes("B2")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="B1"
              className="seat"
              isSelected={selectedSeats.includes("B1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="B2"
              className="seat"
              isSelected={selectedSeats.includes("B2")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="B1"
              className="seat"
              isSelected={selectedSeats.includes("B1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="B2"
              className="seat"
              isSelected={selectedSeats.includes("B2")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="B1"
              className="seat"
              isSelected={selectedSeats.includes("B1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="B2"
              className="seat"
              isSelected={selectedSeats.includes("B2")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="B1"
              className="seat"
              isSelected={selectedSeats.includes("B1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="B2"
              className="seat"
              isSelected={selectedSeats.includes("B2")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="B1"
              className="seat"
              isSelected={selectedSeats.includes("B1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="B2"
              className="seat"
              isSelected={selectedSeats.includes("B2")}
              onClick={handleSeatClick}
            />
          </div>
        </div>
        <div className="seat-container">
          <div className="row">
            <Seat
              seatNumber="A1"
              className="seat"
              isSelected={selectedSeats.includes("A1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A2"
              className="seat"
              isSelected={selectedSeats.includes("A2")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A1"
              className="seat"
              isSelected={selectedSeats.includes("A1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A2"
              className="seat"
              isSelected={selectedSeats.includes("A2")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A1"
              className="seat"
              isSelected={selectedSeats.includes("A1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A2"
              className="seat"
              isSelected={selectedSeats.includes("A2")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A1"
              className="seat"
              isSelected={selectedSeats.includes("A1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A2"
              className="seat"
              isSelected={selectedSeats.includes("A2")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A1"
              className="seat"
              isSelected={selectedSeats.includes("A1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A2"
              className="seat"
              isSelected={selectedSeats.includes("A2")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A1"
              className="seat"
              isSelected={selectedSeats.includes("A1")}
              onClick={handleSeatClick}
            />
            <Seat
              seatNumber="A2"
              className="seat"
              isSelected={selectedSeats.includes("A2")}
              onClick={handleSeatClick}
            />
          </div>
        </div>
        <div className="mt-4">
          <div className="seat-container">
            <div className="row">
              <Seat
                seatNumber="A1"
                className="seat"
                isSelected={selectedSeats.includes("A1")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="A2"
                className="seat"
                isSelected={selectedSeats.includes("A2")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="A1"
                className="seat"
                isSelected={selectedSeats.includes("A1")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="A2"
                className="seat"
                isSelected={selectedSeats.includes("A2")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="A1"
                className="seat"
                isSelected={selectedSeats.includes("A1")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="A2"
                className="seat"
                isSelected={selectedSeats.includes("A2")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="A1"
                className="seat"
                isSelected={selectedSeats.includes("A1")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="A2"
                className="seat"
                isSelected={selectedSeats.includes("A2")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="A1"
                className="seat"
                isSelected={selectedSeats.includes("A1")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="A2"
                className="seat"
                isSelected={selectedSeats.includes("A2")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="A1"
                className="seat"
                isSelected={selectedSeats.includes("A1")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="A2"
                className="seat"
                isSelected={selectedSeats.includes("A2")}
                onClick={handleSeatClick}
              />
            </div>
            <div className="row">
              <Seat
                seatNumber="B1"
                className="seat"
                isSelected={selectedSeats.includes("B1")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="B2"
                className="seat"
                isSelected={selectedSeats.includes("B2")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="B1"
                className="seat"
                isSelected={selectedSeats.includes("B1")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="B2"
                className="seat"
                isSelected={selectedSeats.includes("B2")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="B1"
                className="seat"
                isSelected={selectedSeats.includes("B1")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="B2"
                className="seat"
                isSelected={selectedSeats.includes("B2")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="B1"
                className="seat"
                isSelected={selectedSeats.includes("B1")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="B2"
                className="seat"
                isSelected={selectedSeats.includes("B2")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="B1"
                className="seat"
                isSelected={selectedSeats.includes("B1")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="B2"
                className="seat"
                isSelected={selectedSeats.includes("B2")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="B1"
                className="seat"
                isSelected={selectedSeats.includes("B1")}
                onClick={handleSeatClick}
              />
              <Seat
                seatNumber="B2"
                className="seat"
                isSelected={selectedSeats.includes("B2")}
                onClick={handleSeatClick}
              />
            </div>
          </div>
        </div>
      </div>
      <div>
        <h3>Selected Seats:</h3>
        <ul>
          {selectedSeats.map((seat) => (
            <li key={seat}>{seat}</li>
          ))}
        </ul>
      </div>
    </div>
  );
};

const Seat = ({ seatNumber, isSelected, onClick }) => {
  const seatClass = isSelected ? "seat selected" : "seat";

  return (
    <div className={seatClass} onClick={() => onClick(seatNumber)}>
      {seatNumber}
    </div>
  );
};

export default SeatLayout;
